# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=200)),
                ('command_opt', models.CharField(max_length=300)),
                ('link_ref', models.URLField(max_length=10000)),
                ('description', models.TextField(max_length=200)),
                ('example', models.TextField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
